### ISSUE TITLE
kamon-metrics version update

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [RBMHTechnology/eventuate-tools#28]
please:

https://oss.jfrog.org/oss-release-local/com/rbmhtechnology/eventuate-tools/kamon-metrics_2.11/0.8/kamon-metrics_2.11-0.8.pom

eventuate -> v 0.8.1

kamon -> v 0.6.5 (both 2.11 and 2.12)

**Comment by volkerstampa** [comment]
@Andrei-Pozolotin Thanks for letting me know about the kamon upgrade. Just released 0.8.2 with your proposed changes. Could you please check, if it works for you. Thanks.
