### ISSUE TITLE
Health monitoring

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate-tools#6]
_From @krasserm on September 14, 2015 12:55_

_Copied from original issue: RBMHTechnology/eventuate#110_

**Comment by krasserm** [comment]
_From @Tvaroh on November 21, 2015 17:20_

Free monitoring solutions I am aware of:
- [Typesage monitoring](https://www.typesafe.com/products/typesafe-monitoring)
- [Kamon](http://kamon.io)
- [Funnel](https://oncue.github.io/funnel/)

Are you planning to support one of these or implement something from scratch?

**Comment by krasserm** [comment]
These tools are on also our radar but we haven't decided yet. Reuse is preferred, with specific additions if needed.

**Comment by volkerstampa** [comment]
Initial implementation will be based on [dropwizard's healthchecks lib](http://metrics.dropwizard.io/3.1.0/getting-started/#health-checks).

**Comment by archenroot** [comment]
Without proper monitoring it is hard to convince the management about event driven architectures. You design full process, then you split it into series of events, but in the end you are interested about how your split process ended up. Not by technicel, but by business point of view. I really lik the lightbend intelligent monitoring, but it is not open source...

**Comment by volkerstampa** [comment]
@archenroot Eventuate Tools provides metrics and/or health checks for eventuate internals like the replication progress. The things your are talking about are left to the application. Of course the application could utilize the same metrics libraries like [dropwizard](http://metrics.dropwizard.io/3.1.0/) or [kamon](http://kamon.io/).
